### ISSUE TITLE
Wait for CSS to load in css mount hook

### ISSUE THREAD

**Issue by vladimirtemnikov** [WJSoftware/vite-plugin-single-spa#120]
Hello, thank you for a great lib!

Could we have a check for loaded css links in css lifecycle hook before the next hook with some configurable timeout?

This is already implemented in https://github.com/single-spa/single-spa-css

The problem is that in case if css is not fully loaded there is a possibility of jumping content on page.
If we'll check `load` event on link elements before resolving css hook this could help a lot.

**Comment by webJose** [comment]
Hello, @vladimirtemnikov.  I suppose this would be a nice addition for sure.  If you would like to collaborate, it will be welcomed.  Otherwise, I'll try to get some time to work on it over the weekend or the next weekend.

To be clear and technical:  You want `mountCssFile()` ([code here](https://github.com/WJSoftware/vite-plugin-single-spa/blob/4a96185b15c61e0aa9399568b793f0e6c687bce6/src/multiMife-css.ts#L54)) to return a promise, and to only resolve that promise once the `load` event of the link fires.  Then, have the `mount()` function ([code here](https://github.com/WJSoftware/vite-plugin-single-spa/blob/4a96185b15c61e0aa9399568b793f0e6c687bce6/src/multiMife-css.ts#L29)) modified to collect all promises for all files, and wait for all of them before resolving its own promise.

Finally, perform an equivalent change in the [singleMife-css.ts](https://github.com/WJSoftware/vite-plugin-single-spa/blob/main/src/singleMife-css.ts) file to cover the `singleMife` CSS strategy.  A quick look at this file reveals it might not be too easy to achieve full equivalency, as the `singleMife` strategy creates the links during `bootstrap()` and not during `mount()`.

Would this be the entirety of your enhancement request?

**Comment by webJose** [comment]
Released in v0.7.0.
