### ISSUE TITLE
Option to define where the css file from cssLifecycleFactory is stored

### ISSUE THREAD

**Issue by kennyredstart** [WJSoftware/vite-plugin-single-spa#240]
Currently when building the file is saved in the assets/ folder, however using vue and routing I cannot import files in the assets folder, the url is handled as if it's a routing-url. Can you build the css file into the dist folder? same location as main.js ?

**Comment by webJose** [comment]
Hello. I'm not following.  Can you provide a concrete example or a project repository that shows what you mean?

Here's the thing:  This plug-in does not set the final destination of CSS files.  This is a decision made by Vite.  Whatever Vite outputs, this plug-in uses.  It sounds to me that you need some help with Vite, but since I don't fully understand, I am asking for a more concrete example.

**Comment by kennyredstart** [comment]
I can't seem to wrap my head around it... This is my vite-config:

<img width="908" alt="image" src="https://github.com/user-attachments/assets/4e31a5fa-554a-46e6-aca8-f1dfb6a29035">

and my dist output folder:
<img width="297" alt="image" src="https://github.com/user-attachments/assets/67f3bc53-9c15-478e-be08-e61983e33c30">

I want to have the css folder in the root of the dist, not in the assets folder :(

**Comment by webJose** [comment]
[Vite Config](https://vite.dev/config/build-options.html#build-assetsdir)

**Comment by webJose** [comment]
Closing as this seems to be a Vite question, not an issue.  Feel free to comment or reopen if Vite doesn't resolve your problem and you still believe it has something to do with this plug-in.
